# This is a basic workflow to help you get started with Actions

name: Medium Blogposts Workflow

# Controls when the workflow will run
on:
  schedule: # Run Workflow automatically
    - cron: '0 0 * * *' # Runs ever day at 12am
  workflow_dispatch: # Manually Run Workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-with-blog:
    name: Update repo README with latest medium blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@supertorio"
